### ISSUE TITLE
Analyzer for GetX for explicit implementations

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#91]
```cs
typeof(string).GetMethod(nameof(IConvertible.ToBoolean))
```

**Comment by jnm2** [comment]
`string` has no public or private method named `ToBoolean`, so maybe what the user would have meant was `typeof(IConvertible).GetMethod(nameof(IConvertible.ToBoolean))`?

**Comment by JohanLarsson** [comment]
https://referencesource.microsoft.com/#mscorlib/system/string.cs,3365

Yes we can fix with `typeof(IConvertible).GetMethod(nameof(IConvertible.ToBoolean))` or `InterfaceMap`. I'm thinking a separate analyzer ID may make sense as we can provide more detailed info.

**Comment by jnm2** [comment]
> https://referencesource.microsoft.com/#mscorlib/system/string.cs,3365

Just checking that you know, but in C# that method has no name and in IL that turns into a private method with the exact name `IConvertible.ToBoolean`.

**Comment by JohanLarsson** [comment]
IIRC `typeSymbol.GetMembers()` returns the explicit implementation. And if so we can give a more descriptive warning using this information.
Say we have `typeof(Foo).GetMethod(nameof(Foo.Bar)` and Bar is changed to explicit implementation. Then we can write out what the problem is and write a code fix for it.

**Comment by JohanLarsson** [comment]
Currently `typeof(string).GetMethod(nameof(IConvertible.ToBoolean))`triggers a REFL003 warning, member does not exist.

**Comment by JohanLarsson** [comment]
This is similar to `REFL015` 'Use the containing type.'

**Comment by jnm2** [comment]
> Currently `typeof(string).GetMethod(nameof(IConvertible.ToBoolean))` triggers a REFL003 warning, member does not exist.

Right, because `nameof(IConvertible.ToBoolean)` is `"ToBoolean"` and there is no IL member with the name `ToBoolean` in `string`. C# emits an IL method by convention named `IConvertible.ToBoolean`, but that is an internal implementation detail that could change (like `get_` and `set_` method naming).

> Say we have `typeof(Foo).GetMethod(nameof(Foo.Bar)` and Bar is changed to explicit implementation. Then we can write out what the problem is and write a code fix for it.

Based on this scenario, doesn't it look like right thing to do is to switch to an interface method invocation? Using the interface map to locate the explicit implementation doesn't buy you anything unless you're trying to subvert C#'s interface implementation rules and invoke a base class's explicit implementation when the interface has been reimplemented by the derived class.

**Comment by JohanLarsson** [comment]
So we should fix it by changing to `typeof(IConvertible).GetMethod(nameof(IConvertible.ToBoolean))`?
I have no opinion here, not trying to subvert anything :)

**Comment by jnm2** [comment]
@JohanLarsson I think so. I'm sorry, I didn't mean you were trying to subvert something! There are real-world reasons to invoke using GetInterfaceMap instead of just invoking the interface method, but the point I want to make is that it's very rare and brittle.

**Comment by JohanLarsson** [comment]
How do you feel about separate analyzer for this?

**Comment by jnm2** [comment]
I don't have a feeling one way or the other yet.
